### ISSUE TITLE
Update your project.

### ISSUE THREAD

**Issue by dlopez079** [dlopez079/Python_For_Everyone#6]
Update your project folder.

1. [x] Open up Visual Studio
2. [x] Run the following command: 'git pull origin master'
3. [x] Close this ticket on github.  Use the link on the email to get to the GitHub ticket.
4. [x] Notify me when you finish.

**Comment by Lucswagx** [comment]
Hello, I finished my Issue and now am closing my Ticket. Thank you for setting this for me, I learned a lot.
